### ISSUE TITLE
ModuleNotFoundError: No module named 'digidogs'

### ISSUE THREAD

**Issue by yichuan1998** [mshooter/DigiDogs_release#1]
Thanks for your great job. I followed the instructions to install all the packages and ran "python scripts/demo.py custom data/". And last I got:
![image](https://github.com/mshooter/DigiDogs_release/assets/91551667/459ac2c4-9c20-43fc-98bb-49a3799cface)
This is werid because the terminal showed that digidogs had been installed.
![image](https://github.com/mshooter/DigiDogs_release/assets/91551667/1d1e2cbd-2c50-4455-b1df-0422d8ae0dbf)

**Comment by mshooter** [comment]
@yichuan1998 

This could be an issue, please update your pip version. 
Additionally, I used to run the command 
```
pip install -e . 
```

Let me know if it does not work

**Comment by yichuan1998** [comment]
> @yichuan1998
> 
> This could be an issue, please update your pip version. Additionally, I used to run the command
> 
> ```
> pip install -e . 
> ```
> 
> Let me know if it does not work

It works! Thanks!
